config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resource :session, only: %i[new create destroy]
  resources :questions, except: %i[index show new]
  resources :tags, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :tag_questions, dependent: :destroy
  has_many :tags, through: :tag_questions

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  after_commit :update_tags, on: [:create, :update]

  validates :text, presence: true
  validates :text, length: { maximum: 255 }

  scope :sorted_desc, -> { order(created_at: :desc) }
  scope :with_answers, -> { where.not(answer: nil) }

  def update_tags
    tag_questions.clear
    "#{text} #{answer}".downcase.scan(Tag::TAG_REGEX).uniq.each do |tag|
      tags << Tag.find_or_create_by(name: tag)
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  TAG_REGEX = /#[\wа-яё]+/.freeze

  has_many :tag_questions
  has_many :questions, through: :tag_questions

  before_validation { name&.downcase! }

  validates :name, presence: true

  scope :with_questions, -> { joins(:questions).distinct.order(:name) }
end

app/models/tag_question.rb
class TagQuestion < ApplicationRecord
  belongs_to :tag
  belongs_to :question
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  attr_accessor :password

  # Параметры работы модуля шифрования паролей
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions, dependent: :destroy
  has_many :author_questions,
      class_name: 'Question',
      foreign_key: "author_id",
      dependent: :nullify

  validates :username, :email, presence: true
  validates :username, uniqueness: { case_sensitive: false }
  validates :username, length: { maximum: 40 }
  validates :username, format: {
      with: /\A[A-Za-z0-9_]+\z/, message: "username allows only latin letters, numbers or underscores"
    }

  validates :email, uniqueness: { case_sensitive: false }
  validates :email, format: { with: /\A[\w\d\.-_]+@{1}[\w\d]+\.\w+\z/ }

  validates :profile_bg_color, format: { with: /\A#(?:\h{3}){1,2}\z/ }

  validates :password, presence: true, on: :create
  validates :password, confirmation: true

  before_save :encrypt_password
  before_save :username_and_email_downcase

  def username_and_email_downcase
    self.username = username.downcase
    self.email = email.downcase
  end

  def encrypt_password
    if self.password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      self.password_hash = User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST))
    end
  end

  # Преобразуем бинарную строку в 16-ричный формат для удобства хранения
  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)

    return nil unless user.present?

    pass_hash = User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))

    return nil unless user.password_hash == pass_hash

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Доступ к этой странице запрещен!'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :authorize_user, except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Новый вопрос успешно записан.'
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос обновлен.'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy

    redirect_to user_path(user), notice: 'Вопрос удален.'
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def question_params
    if current_user.present? && params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end

  def check_captcha(model)
    if current_user.present?
      true
    else
      verify_recaptcha(model: model)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user[:id]
      redirect_to root_path, notice: "Добрый день, #{user.username}!"
    else
      flash.now.alert = 'Неправильно указан логин или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Вы разлогинились!'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :load_tag

  def show
    @questions = @tag.questions
  end

  private

  def load_tag
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, except: [:index, :create, :new]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
    @tags = Tag.with_questions
  end

  def new
    redirect_to root_path, alert: 'Вы уже авторизованы на сайте' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_path, alert: 'Вы уже авторизованы на сайте' if current_user.present?
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user[:id]
      redirect_to root_path, notice: 'Вы успешно зарегистрированы!'
    else
      render :new
    end
  end

  def destroy
    if @user.destroy
      session[params[:id]] = nil
      redirect_to root_path, alert: 'Ваш профиль удален!'
    else
      render :edit
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Профиль изменен!'
    else
      render :edit
    end
  end

  def show
    @questions = @user.questions.sorted_desc
    @questions_count = @questions.count
    @answers_count = @questions.with_answers.count
    @unanswered_count = @questions_count - @answers_count

    @new_question = @user.questions.build
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def find_user
    @user ||= User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
            :name, :username, :avatar_link, :profile_bg_color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_link.present?
      user.avatar_link
    else
      asset_path 'avatar.jpg'
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end


  def question_declinated(questions_count)
    word_declination(questions_count, 'вопрос', 'вопроса', 'вопросов')
  end

  def answer_declinated(answers_count)
    word_declination(answers_count, 'ответ', 'ответа', 'ответов')
  end

  def word_declination(number, one, few, many)
    return many if (11..14).include?(number % 100)

    last_digit = number % 10

    return one if last_digit == 1
    return few if (2..4).include?(last_digit)
    many
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <title>Хорошие вопросы</title>
    <script src="https://use.fontawesome.com/aeb8f10254.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
    <div class="header">
      <div class="header-logo">
        <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
      </div>
      <div class="header-nav">
        <% if current_user %>
          <%= link_to "@#{current_user.username}", user_path(current_user) %>  |
          <%= link_to 'Выйти', session_path, data: {method: :delete} %>
        <% else %>
          <%= link_to 'Зарегистрироваться', new_user_path, class: 'button button-light button-small' %>
          <%= link_to 'Войти', new_session_path, class: 'button button-light button-small' %>
        <% end %>
      </div>
    </div>
    <div class="content">
      <div class="container">
        <% if flash.any? %>
          <div class="content-wrapper buffer-both">
            <% flash.each do |name, message| %>
              <%= content_tag :div, message, class: "flash-#{name}" %>
            <% end %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%# Форма для создания/правки вопроса %>
<div class="form">
  <%# Форма для объекта @question %>
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%# Скрытое поле — айдишник юзера, кому задается вопрос %>
    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <%# Простая авторизация - может ли текущий юзер править вопрос? %>
    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <%= recaptcha_tags site_key: '6LcThcwZAAAAAKd3tUUS-GR8pdDR-SnuKmMNQ76h' unless current_user.present? %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">
    <%# Текст вопроса %>
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer %>
      </div>
    <% end %>

    <div class="question-date buffer-both">
      <%= l(question.created_at, format: :short) %>
      <% if question.author.present? %>
        <%= link_to "Автор: #{question.author.name}",
                    user_path(question.author),
                    class: "question-author" %>
      <% end %>
    </div>

    <div class="question-tags">
      <small>
        Тэги: <%= question.tags.map { |t| link_to t.name, tag_path(t) }.join(', ').html_safe %>
      </small>
    </div>
  </div>

  <% if question.user == current_user %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>
    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
              method: :delete, data: {confirm: 'Удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>

app/views/tags/show.html.erb
<h1 class="title-white">Вопросы по тэгу <%= @tag.name %></h1>

<div class="user-questions buffer-both">
  <div class="questions-list">
    <% @questions.each do |question| %>
      <%= render partial: 'questions/question', object: question %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Редактировать профиль</h1>
  <div class="column-1-2">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_link, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Цвет фона вашего профиля', class: 'form-label' %>
        <%= f.color_field :profile_bg_color %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
        <%= link_to 'Удалить профиль', user_path(@user), class: 'button button-red button-small buffer-left', method: :delete, data: {confirm: 'Вы уверены, что хотите удалить ваш профиль и все ваши вопросы?'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%# Этот шаблон отрисуется, когда пользователь захочет посмотреть список пользователей %>
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
        </div>
      </div>
  <% end %>

  <div>
    <% @tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background-color:<%= @user.profile_bg_color %>">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= @questions_count %></h1>
      <p><%= question_declinated(@questions_count) %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @answers_count %></h1>
      <p><%= answer_declinated(@answers_count) %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @unanswered_count %></h1>
      <p>без ответа</p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <%= form_for @new_question do |f| %>
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>

      <%= recaptcha_tags size: 'compact', site_key: '6LcThcwZAAAAAKd3tUUS-GR8pdDR-SnuKmMNQ76h' unless current_user.present? %>

      <div class="form-action">
        <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>